[package]
name = "peer_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
futures = "0.3.31"
local-ip-address = "0.6.5"
tokio = { version = "1.47.0", features = ["full"] }
