services:
  peer1:
    build: .
    command: [ "peer_chat", "client", "-p", "8888" ]
    networks:
      peer_chat_net:
        ipv4_address: 191.0.0.2

  peer2:
    build: .
    command: [ "peer_chat", "client", "-p", "8889" ]  # Different port
    networks:
      peer_chat_net:
        ipv4_address: 191.0.0.3

  peer3:
    build: .
    command: [ "peer_chat", "client", "-p", "8890" ]  # Different port
    networks:
      peer_chat_net:
        ipv4_address: 191.0.0.4

networks:
  peer_chat_net:
    driver: bridge
    ipam:
      config:
        - subnet: 191.0.0.0/24